#include <stdio.h>
int main(){
  char a=0;
  int b=0;
  long c=0;
  printf("a(hex): %p\t a(decimal): %lu\n", &a, &a);
  printf("b(hex): %p\t b(decimal): %lu\n", &b, &b);
  printf("c(hex): %p\t c(decimal): %lu\n", &c, &c);
  char* ap=&a;
  int* bp=&b;
  long* cp=&c;
  printf("ap=%p\n",ap);
  printf("bp=%p\n",bp);
  printf("cp=%p\n",cp);
  *ap=100;
  *bp=101;
  *cp=102;
  printf("a(new)=%d\t b(new)=%d\t c(new)=%d\t\n",a,b,c);
  unsigned int d=256;
  int* dpi=&d;
  char* dpc=&d;
  printf("dpi=%p\t dpi points to:%d\n",dpi,*dpi);
  printf("dpc=%p\t dpc points to:%d\n",dpc,*dpc);
  printf("d=%x\t or %u\n",d,d);
  char* dc=&d;
  printf("d(1st byte)=%hhu\t",*dc);
  dc++;
  printf("d(2nd byte)=%hhu\t",*dc);
  dc++;
  printf("d(3rd byte)=%hhu\t",*dc);
  dc++;
  printf("d(4th byte)=%hhu\n",*dc);
  char* dc2=&d;
  *dc2=*dc2+1;
  dc2++;
  printf("d(1st increment)=%u or %x\n",d,d);
  *dc2=*dc2+1;
  dc2++;
  printf("d(2nd increment)=%u or %x\n",d,d);
  *dc2=*dc2+1;
  dc2++;
  printf("d(3rd increment)=%u or %x\n",d,d);
  *dc2=*dc2+1;
  printf("d(4th increment)=%u or %x\n",d,d);
  d=256;
  char* dc3=&d;
  *dc3=*dc3+16;
  dc3++;
  printf("d(1st increment)=%u or %x\n",d,d);
  *dc3=*dc3+16;
  dc3++;
  printf("d(2nd increment)=%u or %x\n",d,d);
  *dc3=*dc3+16;
  dc3++;
  printf("d(3rd increment)=%u or %x\n",d,d);
  *dc3=*dc3+16;
  printf("d(4th increment)=%u or %x\n",d,d);
}
